/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IProperty__factory } from "./IProperty__factory";
export { PropertyToken__factory } from "./PropertyToken__factory";
