/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IProperty,
  IPropertyInterface,
} from "../../../contracts/PropertyToken.sol/IProperty";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "isWhitelisted",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IProperty__factory {
  static readonly abi = _abi;
  static createInterface(): IPropertyInterface {
    return new utils.Interface(_abi) as IPropertyInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IProperty {
    return new Contract(address, _abi, signerOrProvider) as IProperty;
  }
}
