/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as propertyTokenSol from "./PropertyToken.sol";
export type { propertyTokenSol };
export type { Property } from "./Property";
export type { PropertyVault } from "./PropertyVault";
export type { VerdeBlock } from "./VerdeBlock";
