/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export declare namespace Property {
  export type PropertyDetailsStruct = {
    id: BigNumberish;
    owner: string;
    location: string;
    price: BigNumberish;
    description: string;
    isActive: boolean;
    tokenAddress: string;
  };

  export type PropertyDetailsStructOutput = [
    BigNumber,
    string,
    string,
    BigNumber,
    string,
    boolean,
    string
  ] & {
    id: BigNumber;
    owner: string;
    location: string;
    price: BigNumber;
    description: string;
    isActive: boolean;
    tokenAddress: string;
  };
}

export interface PropertyInterface extends utils.Interface {
  functions: {
    "addProperty(string,uint256,string)": FunctionFragment;
    "approveWhitelist(address)": FunctionFragment;
    "getProperty(uint256)": FunctionFragment;
    "getWhitelistRequests()": FunctionFragment;
    "hasRequested(address)": FunctionFragment;
    "isWhitelisted(address)": FunctionFragment;
    "owner()": FunctionFragment;
    "properties(uint256)": FunctionFragment;
    "propertyCount()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "requestWhitelist()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "whitelistRequests(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addProperty"
      | "approveWhitelist"
      | "getProperty"
      | "getWhitelistRequests"
      | "hasRequested"
      | "isWhitelisted"
      | "owner"
      | "properties"
      | "propertyCount"
      | "renounceOwnership"
      | "requestWhitelist"
      | "transferOwnership"
      | "whitelistRequests"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addProperty",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "approveWhitelist",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getProperty",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getWhitelistRequests",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasRequested",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "isWhitelisted",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "properties",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "propertyCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestWhitelist",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistRequests",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addProperty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProperty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWhitelistRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasRequested",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isWhitelisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "properties", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "propertyCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whitelistRequests",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
    "PropertyAdded(uint256,address,string,uint256,address)": EventFragment;
    "WhitelistRequested(address)": EventFragment;
    "Whitelisted(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PropertyAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "WhitelistRequested"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Whitelisted"): EventFragment;
}

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface PropertyAddedEventObject {
  id: BigNumber;
  owner: string;
  location: string;
  price: BigNumber;
  tokenAddress: string;
}
export type PropertyAddedEvent = TypedEvent<
  [BigNumber, string, string, BigNumber, string],
  PropertyAddedEventObject
>;

export type PropertyAddedEventFilter = TypedEventFilter<PropertyAddedEvent>;

export interface WhitelistRequestedEventObject {
  investor: string;
}
export type WhitelistRequestedEvent = TypedEvent<
  [string],
  WhitelistRequestedEventObject
>;

export type WhitelistRequestedEventFilter =
  TypedEventFilter<WhitelistRequestedEvent>;

export interface WhitelistedEventObject {
  investor: string;
}
export type WhitelistedEvent = TypedEvent<[string], WhitelistedEventObject>;

export type WhitelistedEventFilter = TypedEventFilter<WhitelistedEvent>;

export interface Property extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PropertyInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addProperty(
      _location: string,
      _price: BigNumberish,
      _description: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    approveWhitelist(
      investor: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    getProperty(
      _id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[Property.PropertyDetailsStructOutput]>;

    getWhitelistRequests(overrides?: CallOverrides): Promise<[string[]]>;

    hasRequested(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    isWhitelisted(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    properties(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, string, BigNumber, string, boolean, string] & {
        id: BigNumber;
        owner: string;
        location: string;
        price: BigNumber;
        description: string;
        isActive: boolean;
        tokenAddress: string;
      }
    >;

    propertyCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    requestWhitelist(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    whitelistRequests(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  addProperty(
    _location: string,
    _price: BigNumberish,
    _description: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  approveWhitelist(
    investor: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  getProperty(
    _id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<Property.PropertyDetailsStructOutput>;

  getWhitelistRequests(overrides?: CallOverrides): Promise<string[]>;

  hasRequested(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  isWhitelisted(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  owner(overrides?: CallOverrides): Promise<string>;

  properties(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, string, string, BigNumber, string, boolean, string] & {
      id: BigNumber;
      owner: string;
      location: string;
      price: BigNumber;
      description: string;
      isActive: boolean;
      tokenAddress: string;
    }
  >;

  propertyCount(overrides?: CallOverrides): Promise<BigNumber>;

  renounceOwnership(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  requestWhitelist(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  whitelistRequests(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    addProperty(
      _location: string,
      _price: BigNumberish,
      _description: string,
      overrides?: CallOverrides
    ): Promise<void>;

    approveWhitelist(
      investor: string,
      overrides?: CallOverrides
    ): Promise<void>;

    getProperty(
      _id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<Property.PropertyDetailsStructOutput>;

    getWhitelistRequests(overrides?: CallOverrides): Promise<string[]>;

    hasRequested(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    isWhitelisted(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    owner(overrides?: CallOverrides): Promise<string>;

    properties(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, string, BigNumber, string, boolean, string] & {
        id: BigNumber;
        owner: string;
        location: string;
        price: BigNumber;
        description: string;
        isActive: boolean;
        tokenAddress: string;
      }
    >;

    propertyCount(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    requestWhitelist(overrides?: CallOverrides): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    whitelistRequests(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;

    "PropertyAdded(uint256,address,string,uint256,address)"(
      id?: BigNumberish | null,
      owner?: string | null,
      location?: null,
      price?: null,
      tokenAddress?: null
    ): PropertyAddedEventFilter;
    PropertyAdded(
      id?: BigNumberish | null,
      owner?: string | null,
      location?: null,
      price?: null,
      tokenAddress?: null
    ): PropertyAddedEventFilter;

    "WhitelistRequested(address)"(
      investor?: string | null
    ): WhitelistRequestedEventFilter;
    WhitelistRequested(investor?: string | null): WhitelistRequestedEventFilter;

    "Whitelisted(address)"(investor?: string | null): WhitelistedEventFilter;
    Whitelisted(investor?: string | null): WhitelistedEventFilter;
  };

  estimateGas: {
    addProperty(
      _location: string,
      _price: BigNumberish,
      _description: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    approveWhitelist(
      investor: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    getProperty(
      _id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getWhitelistRequests(overrides?: CallOverrides): Promise<BigNumber>;

    hasRequested(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    isWhitelisted(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    properties(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    propertyCount(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    requestWhitelist(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    whitelistRequests(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addProperty(
      _location: string,
      _price: BigNumberish,
      _description: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    approveWhitelist(
      investor: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    getProperty(
      _id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getWhitelistRequests(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hasRequested(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isWhitelisted(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    properties(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    propertyCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    requestWhitelist(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    whitelistRequests(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
