/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export interface VerdeBlockInterface extends utils.Interface {
  functions: {
    "createProperty(string,uint256,string)": FunctionFragment;
    "getProperties()": FunctionFragment;
    "getProperty(uint256)": FunctionFragment;
    "owner()": FunctionFragment;
    "properties(uint256)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "whitelistInvestor(uint256,address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "createProperty"
      | "getProperties"
      | "getProperty"
      | "owner"
      | "properties"
      | "renounceOwnership"
      | "transferOwnership"
      | "whitelistInvestor"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createProperty",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getProperties",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProperty",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "properties",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistInvestor",
    values: [BigNumberish, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "createProperty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProperties",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProperty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "properties", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whitelistInvestor",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
    "PropertyCreated(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PropertyCreated"): EventFragment;
}

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface PropertyCreatedEventObject {
  propertyAddress: string;
  propertyId: BigNumber;
}
export type PropertyCreatedEvent = TypedEvent<
  [string, BigNumber],
  PropertyCreatedEventObject
>;

export type PropertyCreatedEventFilter = TypedEventFilter<PropertyCreatedEvent>;

export interface VerdeBlock extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: VerdeBlockInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    createProperty(
      _location: string,
      _price: BigNumberish,
      _description: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    getProperties(overrides?: CallOverrides): Promise<[string[]]>;

    getProperty(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    properties(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    whitelistInvestor(
      propertyIndex: BigNumberish,
      investor: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  createProperty(
    _location: string,
    _price: BigNumberish,
    _description: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  getProperties(overrides?: CallOverrides): Promise<string[]>;

  getProperty(index: BigNumberish, overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  properties(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  whitelistInvestor(
    propertyIndex: BigNumberish,
    investor: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    createProperty(
      _location: string,
      _price: BigNumberish,
      _description: string,
      overrides?: CallOverrides
    ): Promise<void>;

    getProperties(overrides?: CallOverrides): Promise<string[]>;

    getProperty(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    properties(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    whitelistInvestor(
      propertyIndex: BigNumberish,
      investor: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;

    "PropertyCreated(address,uint256)"(
      propertyAddress?: string | null,
      propertyId?: BigNumberish | null
    ): PropertyCreatedEventFilter;
    PropertyCreated(
      propertyAddress?: string | null,
      propertyId?: BigNumberish | null
    ): PropertyCreatedEventFilter;
  };

  estimateGas: {
    createProperty(
      _location: string,
      _price: BigNumberish,
      _description: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    getProperties(overrides?: CallOverrides): Promise<BigNumber>;

    getProperty(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    properties(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    whitelistInvestor(
      propertyIndex: BigNumberish,
      investor: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createProperty(
      _location: string,
      _price: BigNumberish,
      _description: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    getProperties(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getProperty(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    properties(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    whitelistInvestor(
      propertyIndex: BigNumberish,
      investor: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
