/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as propertyTokenSol from "./PropertyToken.sol";
export { Property__factory } from "./Property__factory";
export { PropertyVault__factory } from "./PropertyVault__factory";
